name: models #название папки где расположено pubspec.yaml
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.4
  cloud_firestore: ^3.1.16
  firebase_auth: ^3.3.18
  provider: ^6.0.3
  fluttertoast: ^8.0.9 
  firebase_core: ^1.17.0
  curved_navigation_bar: ^1.0.3
  flutter_mobile_vision: ^0.1.4+1
  scan: ^1.6.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true